Laboratorio 1
=================
Esercitazione numpy

In [1]:
from numpy  import *

Important: NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is rank.

In [2]:
a = arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

# Array creation

In [12]:
monodimensional = array([1,2,3,4])

In [13]:
bidimensional = array( [ (1.5,2,3), (4,5,6) ] )

In [14]:
monodimensional

array([1, 2, 3, 4])

In [15]:
bidimensional

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [16]:
complex = array( [ [1,2], [3,4] ], dtype=complex )

In [17]:
complex

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [18]:
print arange(100) #in range [0,100]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [19]:
print arange(10000) #too big to be printed entirely

[   0    1    2 ..., 9997 9998 9999]


In [20]:
print arange(10000).reshape(100,100)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [21]:
a = arange(20)

In [22]:
b = arange (20,40)

In [23]:
a*b

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300, 341, 384,
       429, 476, 525, 576, 629, 684, 741])

# More functions

In [24]:
10*sin(a) #sin function

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495,
       -9.58924275, -2.79415498,  6.56986599,  9.89358247,  4.12118485,
       -5.44021111, -9.99990207, -5.36572918,  4.20167037,  9.90607356,
        6.5028784 , -2.87903317, -9.61397492, -7.50987247,  1.4987721 ])

In [25]:
b = random.random((2,3))

In [26]:
b

array([[ 0.8594531 ,  0.18824045,  0.68040725],
       [ 0.68934869,  0.13643708,  0.8088377 ]])

In [27]:
a = ones(3, dtype=int32)

In [28]:
a

array([1, 1, 1], dtype=int32)

In [29]:
b = linspace(0,pi,3)

In [30]:
b

array([ 0.        ,  1.57079633,  3.14159265])

In [31]:
B = arange(3)

In [32]:
sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [48]:
a = arange(10)**3